/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from './mocks/index.js';
export type { mocks };
export type { StakingContract } from './StakingContract.js';
export * as factories from './factories/index.js';
export type { MockERC20 } from './mocks/MockERC20.js';
export { MockERC20__factory } from './factories/mocks/MockERC20__factory.js';
export { StakingContract__factory } from './factories/StakingContract__factory.js';