/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace StakingContract {
      
    export type PlanStruct = {period: BigNumberish, apr: BigNumberish, penalty: BigNumberish}

    export type PlanStructOutput = [period: bigint, apr: bigint, penalty: bigint] & {period: bigint, apr: bigint, penalty: bigint }
  

    export type StakeStruct = {planId: BigNumberish, amount: BigNumberish, apr: BigNumberish, penalty: BigNumberish, startTime: BigNumberish, endTime: BigNumberish, staker: AddressLike}

    export type StakeStructOutput = [planId: bigint, amount: bigint, apr: bigint, penalty: bigint, startTime: bigint, endTime: bigint, staker: string] & {planId: bigint, amount: bigint, apr: bigint, penalty: bigint, startTime: bigint, endTime: bigint, staker: string }
  
    }

  export interface StakingContractInterface extends Interface {
    getFunction(nameOrSignature: "UPGRADE_INTERFACE_VERSION" | "addPlan" | "createStake" | "depositRewards" | "getPlan" | "getRewardPool" | "getStake" | "getStakeCountByUser" | "getStakeIdsByUser" | "getStakesByUser" | "getTotalStaked" | "getTotalStakers" | "implementation" | "initialize" | "owner" | "pause" | "paused" | "pendingReward" | "proxiableUUID" | "renounceOwnership" | "rewardPool" | "stakingToken" | "totalStaked" | "totalStakers" | "transferOwnership" | "unpause" | "unstake" | "updatePlan" | "upgradeToAndCall"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Initialized" | "OwnershipTransferred" | "Paused" | "PlanAdded" | "PlanUpdated" | "StakeCreated" | "Unpaused" | "Unstaked" | "Upgraded"): EventFragment;

    encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'addPlan', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createStake', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositRewards', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPlan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRewardPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'getStake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getStakeCountByUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getStakeIdsByUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getStakesByUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTotalStaked', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTotalStakers', values?: undefined): string;
encodeFunctionData(functionFragment: 'implementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingReward', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'stakingToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalStaked', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalStakers', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'unstake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updatePlan', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addPlan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPlan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRewardPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStakeCountByUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStakeIdsByUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStakesByUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalStaked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalStakers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'implementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalStaked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalStakers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePlan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
  }

  
    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlanAddedEvent {
      export type InputTuple = [planId: BigNumberish, period: BigNumberish, apr: BigNumberish, penalty: BigNumberish];
      export type OutputTuple = [planId: bigint, period: bigint, apr: bigint, penalty: bigint];
      export interface OutputObject {planId: bigint, period: bigint, apr: bigint, penalty: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlanUpdatedEvent {
      export type InputTuple = [planId: BigNumberish, period: BigNumberish, apr: BigNumberish, penalty: BigNumberish];
      export type OutputTuple = [planId: bigint, period: bigint, apr: bigint, penalty: bigint];
      export interface OutputObject {planId: bigint, period: bigint, apr: bigint, penalty: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeCreatedEvent {
      export type InputTuple = [stakeId: BigNumberish, staker: AddressLike, planId: BigNumberish, amount: BigNumberish, apr: BigNumberish, penalty: BigNumberish];
      export type OutputTuple = [stakeId: bigint, staker: string, planId: bigint, amount: bigint, apr: bigint, penalty: bigint];
      export interface OutputObject {stakeId: bigint, staker: string, planId: bigint, amount: bigint, apr: bigint, penalty: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakedEvent {
      export type InputTuple = [stakeId: BigNumberish, staker: AddressLike, amount: BigNumberish, reward: BigNumberish];
      export type OutputTuple = [stakeId: bigint, staker: string, amount: bigint, reward: bigint];
      export interface OutputObject {stakeId: bigint, staker: string, amount: bigint, reward: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StakingContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): StakingContract;
    waitForDeployment(): Promise<this>;

    interface: StakingContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addPlan: TypedContractMethod<
      [_days: BigNumberish, _apr: BigNumberish, _penalty: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createStake: TypedContractMethod<
      [_planId: BigNumberish, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    depositRewards: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getPlan: TypedContractMethod<
      [_planId: BigNumberish, ],
      [StakingContract.PlanStructOutput],
      'view'
    >
    

    
    getRewardPool: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getStake: TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [StakingContract.StakeStructOutput],
      'view'
    >
    

    
    getStakeCountByUser: TypedContractMethod<
      [_user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getStakeIdsByUser: TypedContractMethod<
      [_user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getStakesByUser: TypedContractMethod<
      [_user: AddressLike, ],
      [StakingContract.StakeStructOutput[]],
      'view'
    >
    

    
    getTotalStaked: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTotalStakers: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    implementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_stakingToken: AddressLike, initialOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    pendingReward: TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rewardPool: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    stakingToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalStaked: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalStakers: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    unstake: TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updatePlan: TypedContractMethod<
      [_planId: BigNumberish, _days: BigNumberish, _apr: BigNumberish, _penalty: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addPlan'): TypedContractMethod<
      [_days: BigNumberish, _apr: BigNumberish, _penalty: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createStake'): TypedContractMethod<
      [_planId: BigNumberish, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositRewards'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPlan'): TypedContractMethod<
      [_planId: BigNumberish, ],
      [StakingContract.PlanStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRewardPool'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getStake'): TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [StakingContract.StakeStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getStakeCountByUser'): TypedContractMethod<
      [_user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getStakeIdsByUser'): TypedContractMethod<
      [_user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getStakesByUser'): TypedContractMethod<
      [_user: AddressLike, ],
      [StakingContract.StakeStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalStaked'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalStakers'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'implementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_stakingToken: AddressLike, initialOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pendingReward'): TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardPool'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'stakingToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalStaked'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalStakers'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unstake'): TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePlan'): TypedContractMethod<
      [_planId: BigNumberish, _days: BigNumberish, _apr: BigNumberish, _penalty: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;

    getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PlanAdded'): TypedContractEvent<PlanAddedEvent.InputTuple, PlanAddedEvent.OutputTuple, PlanAddedEvent.OutputObject>;
getEvent(key: 'PlanUpdated'): TypedContractEvent<PlanUpdatedEvent.InputTuple, PlanUpdatedEvent.OutputTuple, PlanUpdatedEvent.OutputObject>;
getEvent(key: 'StakeCreated'): TypedContractEvent<StakeCreatedEvent.InputTuple, StakeCreatedEvent.OutputTuple, StakeCreatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'Unstaked'): TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;

    filters: {
      
      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PlanAdded(uint256,uint256,uint256,uint256)': TypedContractEvent<PlanAddedEvent.InputTuple, PlanAddedEvent.OutputTuple, PlanAddedEvent.OutputObject>;
      PlanAdded: TypedContractEvent<PlanAddedEvent.InputTuple, PlanAddedEvent.OutputTuple, PlanAddedEvent.OutputObject>;
    

      'PlanUpdated(uint256,uint256,uint256,uint256)': TypedContractEvent<PlanUpdatedEvent.InputTuple, PlanUpdatedEvent.OutputTuple, PlanUpdatedEvent.OutputObject>;
      PlanUpdated: TypedContractEvent<PlanUpdatedEvent.InputTuple, PlanUpdatedEvent.OutputTuple, PlanUpdatedEvent.OutputObject>;
    

      'StakeCreated(uint256,address,uint256,uint256,uint256,uint256)': TypedContractEvent<StakeCreatedEvent.InputTuple, StakeCreatedEvent.OutputTuple, StakeCreatedEvent.OutputObject>;
      StakeCreated: TypedContractEvent<StakeCreatedEvent.InputTuple, StakeCreatedEvent.OutputTuple, StakeCreatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'Unstaked(uint256,address,uint256,uint256)': TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
      Unstaked: TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }