/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace StakingContract {
      
    export type PlanStruct = {period: BigNumberish, apr: BigNumberish, penalty: BigNumberish, active: boolean}

    export type PlanStructOutput = [period: bigint, apr: bigint, penalty: bigint, active: boolean] & {period: bigint, apr: bigint, penalty: bigint, active: boolean }
  

    export type StakeStruct = {planId: BigNumberish, stakeId: BigNumberish, token: AddressLike, amount: BigNumberish, startTime: BigNumberish, endTime: BigNumberish, lastClaimTime: BigNumberish, claimedReward: BigNumberish, staker: AddressLike}

    export type StakeStructOutput = [planId: bigint, stakeId: bigint, token: string, amount: bigint, startTime: bigint, endTime: bigint, lastClaimTime: bigint, claimedReward: bigint, staker: string] & {planId: bigint, stakeId: bigint, token: string, amount: bigint, startTime: bigint, endTime: bigint, lastClaimTime: bigint, claimedReward: bigint, staker: string }
  
    }

  export interface StakingContractInterface extends Interface {
    getFunction(nameOrSignature: "addPlan" | "addToken" | "claimReward" | "createStake" | "deletePlan" | "depositRewards" | "getPlan" | "getStake" | "getStakesByUser" | "owner" | "pendingReward" | "renounceOwnership" | "transferOwnership" | "unstake" | "updatePlan"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "PlanAdded" | "PlanDeleted" | "PlanUpdated" | "RewardClaimed" | "StakeCreated" | "TokenAdded" | "Unstaked"): EventFragment;

    encodeFunctionData(functionFragment: 'addPlan', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'addToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claimReward', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createStake', values: [BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deletePlan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'depositRewards', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPlan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getStake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getStakesByUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingReward', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unstake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updatePlan', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addPlan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deletePlan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPlan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStakesByUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePlan', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlanAddedEvent {
      export type InputTuple = [planId: BigNumberish, period: BigNumberish, apr: BigNumberish, penalty: BigNumberish];
      export type OutputTuple = [planId: bigint, period: bigint, apr: bigint, penalty: bigint];
      export interface OutputObject {planId: bigint, period: bigint, apr: bigint, penalty: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlanDeletedEvent {
      export type InputTuple = [planId: BigNumberish];
      export type OutputTuple = [planId: bigint];
      export interface OutputObject {planId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlanUpdatedEvent {
      export type InputTuple = [planId: BigNumberish, period: BigNumberish, apr: BigNumberish, penalty: BigNumberish];
      export type OutputTuple = [planId: bigint, period: bigint, apr: bigint, penalty: bigint];
      export interface OutputObject {planId: bigint, period: bigint, apr: bigint, penalty: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardClaimedEvent {
      export type InputTuple = [stakeId: BigNumberish, staker: AddressLike, reward: BigNumberish];
      export type OutputTuple = [stakeId: bigint, staker: string, reward: bigint];
      export interface OutputObject {stakeId: bigint, staker: string, reward: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeCreatedEvent {
      export type InputTuple = [stakeId: BigNumberish, staker: AddressLike, planId: BigNumberish, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [stakeId: bigint, staker: string, planId: bigint, token: string, amount: bigint];
      export interface OutputObject {stakeId: bigint, staker: string, planId: bigint, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenAddedEvent {
      export type InputTuple = [token: AddressLike];
      export type OutputTuple = [token: string];
      export interface OutputObject {token: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakedEvent {
      export type InputTuple = [stakeId: BigNumberish, staker: AddressLike, amount: BigNumberish, reward: BigNumberish];
      export type OutputTuple = [stakeId: bigint, staker: string, amount: bigint, reward: bigint];
      export interface OutputObject {stakeId: bigint, staker: string, amount: bigint, reward: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StakingContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): StakingContract;
    waitForDeployment(): Promise<this>;

    interface: StakingContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addPlan: TypedContractMethod<
      [_days: BigNumberish, _apr: BigNumberish, _penalty: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    addToken: TypedContractMethod<
      [_token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    claimReward: TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createStake: TypedContractMethod<
      [_planId: BigNumberish, _token: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    deletePlan: TypedContractMethod<
      [_planId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    depositRewards: TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getPlan: TypedContractMethod<
      [_planId: BigNumberish, ],
      [StakingContract.PlanStructOutput],
      'view'
    >
    

    
    getStake: TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [StakingContract.StakeStructOutput],
      'view'
    >
    

    
    getStakesByUser: TypedContractMethod<
      [_user: AddressLike, ],
      [StakingContract.StakeStructOutput[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingReward: TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unstake: TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updatePlan: TypedContractMethod<
      [_planId: BigNumberish, _days: BigNumberish, _apr: BigNumberish, _penalty: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addPlan'): TypedContractMethod<
      [_days: BigNumberish, _apr: BigNumberish, _penalty: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addToken'): TypedContractMethod<
      [_token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimReward'): TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createStake'): TypedContractMethod<
      [_planId: BigNumberish, _token: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deletePlan'): TypedContractMethod<
      [_planId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositRewards'): TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPlan'): TypedContractMethod<
      [_planId: BigNumberish, ],
      [StakingContract.PlanStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getStake'): TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [StakingContract.StakeStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getStakesByUser'): TypedContractMethod<
      [_user: AddressLike, ],
      [StakingContract.StakeStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingReward'): TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unstake'): TypedContractMethod<
      [_stakeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePlan'): TypedContractMethod<
      [_planId: BigNumberish, _days: BigNumberish, _apr: BigNumberish, _penalty: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PlanAdded'): TypedContractEvent<PlanAddedEvent.InputTuple, PlanAddedEvent.OutputTuple, PlanAddedEvent.OutputObject>;
getEvent(key: 'PlanDeleted'): TypedContractEvent<PlanDeletedEvent.InputTuple, PlanDeletedEvent.OutputTuple, PlanDeletedEvent.OutputObject>;
getEvent(key: 'PlanUpdated'): TypedContractEvent<PlanUpdatedEvent.InputTuple, PlanUpdatedEvent.OutputTuple, PlanUpdatedEvent.OutputObject>;
getEvent(key: 'RewardClaimed'): TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
getEvent(key: 'StakeCreated'): TypedContractEvent<StakeCreatedEvent.InputTuple, StakeCreatedEvent.OutputTuple, StakeCreatedEvent.OutputObject>;
getEvent(key: 'TokenAdded'): TypedContractEvent<TokenAddedEvent.InputTuple, TokenAddedEvent.OutputTuple, TokenAddedEvent.OutputObject>;
getEvent(key: 'Unstaked'): TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PlanAdded(uint256,uint256,uint256,uint256)': TypedContractEvent<PlanAddedEvent.InputTuple, PlanAddedEvent.OutputTuple, PlanAddedEvent.OutputObject>;
      PlanAdded: TypedContractEvent<PlanAddedEvent.InputTuple, PlanAddedEvent.OutputTuple, PlanAddedEvent.OutputObject>;
    

      'PlanDeleted(uint256)': TypedContractEvent<PlanDeletedEvent.InputTuple, PlanDeletedEvent.OutputTuple, PlanDeletedEvent.OutputObject>;
      PlanDeleted: TypedContractEvent<PlanDeletedEvent.InputTuple, PlanDeletedEvent.OutputTuple, PlanDeletedEvent.OutputObject>;
    

      'PlanUpdated(uint256,uint256,uint256,uint256)': TypedContractEvent<PlanUpdatedEvent.InputTuple, PlanUpdatedEvent.OutputTuple, PlanUpdatedEvent.OutputObject>;
      PlanUpdated: TypedContractEvent<PlanUpdatedEvent.InputTuple, PlanUpdatedEvent.OutputTuple, PlanUpdatedEvent.OutputObject>;
    

      'RewardClaimed(uint256,address,uint256)': TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
      RewardClaimed: TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
    

      'StakeCreated(uint256,address,uint256,address,uint256)': TypedContractEvent<StakeCreatedEvent.InputTuple, StakeCreatedEvent.OutputTuple, StakeCreatedEvent.OutputObject>;
      StakeCreated: TypedContractEvent<StakeCreatedEvent.InputTuple, StakeCreatedEvent.OutputTuple, StakeCreatedEvent.OutputObject>;
    

      'TokenAdded(address)': TypedContractEvent<TokenAddedEvent.InputTuple, TokenAddedEvent.OutputTuple, TokenAddedEvent.OutputObject>;
      TokenAdded: TypedContractEvent<TokenAddedEvent.InputTuple, TokenAddedEvent.OutputTuple, TokenAddedEvent.OutputObject>;
    

      'Unstaked(uint256,address,uint256,uint256)': TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
      Unstaked: TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
    
    };
  }